### ISSUE TITLE
TypeScript declaration seems wrong

### ISSUE THREAD

**Issue by callumlocke** [jesseditson/fs-router#19]
Thanks for writing this library, it looks great. But I've tried to use it with a TypeScript project and it gives me an error when I try to call `matched(req, res)`:

```
Argument of type 'IncomingMessage' is not assignable to parameter of type 'FSRouterIncomingMessage'.
  Type 'IncomingMessage' is missing the following properties from type 'FSRouterIncomingMessage': params, queryts(2345)
```

Looking at fs-router's bundled [TypeScript declaration](https://github.com/jesseditson/fs-router/blob/master/index.d.ts), it says the request handler returned by fs-micro takes a customized `req`, adding `params` and `query` objects:

```ts
    interface FSRouterIncomingMessage extends IncomingMessage {
        params: {
            [paramName: string]: string
        },
        query: {
            [paramName: string]: string
        }
    }
```

But why? Micro doesn't add these extra properties to `req`. According to its own TypeScript declarations (in both the latest [DefinitelyTyped package](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/micro/index.d.ts#L11) and the [bundled declaration](https://github.com/zeit/micro/blob/v9.3.5-canary.3/packages/micro/micro.d.ts#L5) included in the latest Canary release of micro itself), the `req` argument is just a standard `IncomingMessage`. Where are these `params` and `query` properties supposed to come from?

**Comment by callumlocke** [comment]
OK, looking a bit closer at the TypeScript example, it seems I'm supposed to import `RequestHandler` from fs-router, and use that to type my micro handler. But while that might pass type-checking in the example, it's a hack and could cause problems in real code. The micro handler doesn't really implement `fsRouter.RequestHandler`. It seems this hack is suggested because the `match(req)` call actually modifies `req` so it's a different type after the call. I'm not sure if there's any correct way to represent this in TypeScript.

**Comment by jesseditson** [comment]
Since this library extends req (a pattern you are welcome to take issue with, but also just a fact in the library’s current architecture), using a type that extends IncomingMessage seems correct to me - I don’t believe it’s a hack at all to provide a type for the object that this library returns.

That said, I’m not sure that any architecture change would get you to a place where you could write anonymous handlers without assigning them a type. Right now typing your handlers as RequestHandler will solve your problem cleanly. If query and params were to be passed as arguments rather than added to req you’d still need this.

If I were to write this lib from scratch I might consider returning parsers from it (like micro) for parsing query and params functionally, which would leave alone the req, but that would break existing code so I’d need to bump major. Would be happy to consider a PR doing just that if it seems preferable, I could release that under a tag. In any case, this is a design critique rather than a bug so I’ll close this issue.
